import React from 'react';
import {
    UserOutlined,
    TeamOutlined,
    CrownOutlined,
    EditOutlined,
    PlusOutlined,
    ReloadOutlined,
    DeleteOutlined,
    CheckCircleOutlined,
    CloseCircleOutlined,
    ExclamationCircleOutlined,
    InfoCircleOutlined,
    SettingOutlined,
    DashboardOutlined,
    ProjectOutlined,
    CloudOutlined,
    FileOutlined,
    FileTextOutlined,
    FolderOutlined,
    SecurityScanOutlined,
    KeyOutlined,
    BellOutlined,
    CheckSquareOutlined,
    QuestionCircleOutlined,
    GlobalOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    SmileOutlined,
    PlayCircleOutlined,
    StopOutlined,
    SyncOutlined,
    HistoryOutlined,
    MonitorOutlined,
    DatabaseOutlined,
    PartitionOutlined,
    ClusterOutlined,
    GatewayOutlined,
    NodeIndexOutlined,
    ControlOutlined,
    LockOutlined,
    UnlockOutlined,
    LinkOutlined,
    ShareAltOutlined,
    CloudUploadOutlined,
    CloudDownloadOutlined,
    HomeOutlined,
    LogoutOutlined,
    UserSwitchOutlined,
    QuestionOutlined,
    TransactionOutlined,
    AppstoreOutlined,
    DeploymentUnitOutlined,
    ApartmentOutlined,
    FileSearchOutlined,
    FileDoneOutlined,
    FileAddOutlined,
    FolderAddOutlined,
    CloudServerOutlined,
    RocketOutlined,
    SafetyOutlined,
    AuditOutlined,
    BarsOutlined,
    BlockOutlined,
    BranchesOutlined,
    CarryOutOutlined,
    FieldTimeOutlined,
    FileProtectOutlined,
    MessageOutlined,
    ReadOutlined,
    SearchOutlined,
    ToolOutlined,
    VerifiedOutlined,
    RobotOutlined,
    CommentOutlined,
    CustomerServiceOutlined,
    BulbOutlined,
    ThunderboltOutlined,
    ExperimentOutlined,
    ScheduleOutlined,
    PieChartOutlined,
    DesktopOutlined,
    AlertOutlined,
    BarChartOutlined,
    BankOutlined,
    FormOutlined,
    FundOutlined,
} from '@ant-design/icons';

/**
 * 核心图标映射表
 * 
 * 优化点：
 * 避免在 app.tsx 中使用 import * as Icons，从而允许 Webpack/Mako 进行更好的 Tree Shaking。
 * 这里显式列出管理系统中常用的图标。
 */
export const CORE_ICON_MAP: Record<string, React.ReactNode> = {
    UserOutlined: <UserOutlined />,
    TeamOutlined: <TeamOutlined />,
    CrownOutlined: <CrownOutlined />,
    EditOutlined: <EditOutlined />,
    PlusOutlined: <PlusOutlined />,
    ReloadOutlined: <ReloadOutlined />,
    DeleteOutlined: <DeleteOutlined />,
    CheckCircleOutlined: <CheckCircleOutlined />,
    CloseCircleOutlined: <CloseCircleOutlined />,
    ExclamationCircleOutlined: <ExclamationCircleOutlined />,
    InfoCircleOutlined: <InfoCircleOutlined />,
    SettingOutlined: <SettingOutlined />,
    DashboardOutlined: <DashboardOutlined />,
    ProjectOutlined: <ProjectOutlined />,
    CloudOutlined: <CloudOutlined />,
    FileOutlined: <FileOutlined />,
    FileTextOutlined: <FileTextOutlined />,
    FolderOutlined: <FolderOutlined />,
    SecurityScanOutlined: <SecurityScanOutlined />,
    KeyOutlined: <KeyOutlined />,
    BellOutlined: <BellOutlined />,
    CheckSquareOutlined: <CheckSquareOutlined />,
    QuestionCircleOutlined: <QuestionCircleOutlined />,
    GlobalOutlined: <GlobalOutlined />,
    MenuFoldOutlined: <MenuFoldOutlined />,
    MenuUnfoldOutlined: <MenuUnfoldOutlined />,
    SmileOutlined: <SmileOutlined />,
    PlayCircleOutlined: <PlayCircleOutlined />,
    StopOutlined: <StopOutlined />,
    SyncOutlined: <SyncOutlined />,
    HistoryOutlined: <HistoryOutlined />,
    MonitorOutlined: <MonitorOutlined />,
    DatabaseOutlined: <DatabaseOutlined />,
    PartitionOutlined: <PartitionOutlined />,
    ClusterOutlined: <ClusterOutlined />,
    GatewayOutlined: <GatewayOutlined />,
    NodeIndexOutlined: <NodeIndexOutlined />,
    ControlOutlined: <ControlOutlined />,
    LockOutlined: <LockOutlined />,
    UnlockOutlined: <UnlockOutlined />,
    LinkOutlined: <LinkOutlined />,
    ShareAltOutlined: <ShareAltOutlined />,
    CloudUploadOutlined: <CloudUploadOutlined />,
    CloudDownloadOutlined: <CloudDownloadOutlined />,
    HomeOutlined: <HomeOutlined />,
    LogoutOutlined: <LogoutOutlined />,
    UserSwitchOutlined: <UserSwitchOutlined />,
    QuestionOutlined: <QuestionOutlined />,
    TransactionOutlined: <TransactionOutlined />,
    AppstoreOutlined: <AppstoreOutlined />,
    DeploymentUnitOutlined: <DeploymentUnitOutlined />,
    ApartmentOutlined: <ApartmentOutlined />,
    FileSearchOutlined: <FileSearchOutlined />,
    FileDoneOutlined: <FileDoneOutlined />,
    FileAddOutlined: <FileAddOutlined />,
    FolderAddOutlined: <FolderAddOutlined />,
    CloudServerOutlined: <CloudServerOutlined />,
    RocketOutlined: <RocketOutlined />,
    SafetyOutlined: <SafetyOutlined />,
    AuditOutlined: <AuditOutlined />,
    BarsOutlined: <BarsOutlined />,
    BlockOutlined: <BlockOutlined />,
    BranchesOutlined: <BranchesOutlined />,
    CarryOutOutlined: <CarryOutOutlined />,
    FieldTimeOutlined: <FieldTimeOutlined />,
    FileProtectOutlined: <FileProtectOutlined />,
    MessageOutlined: <MessageOutlined />,
    ReadOutlined: <ReadOutlined />,
    SearchOutlined: <SearchOutlined />,
    ToolOutlined: <ToolOutlined />,
    VerifiedOutlined: <VerifiedOutlined />,
    RobotOutlined: <RobotOutlined />,
    CommentOutlined: <CommentOutlined />,
    CustomerServiceOutlined: <CustomerServiceOutlined />,
    BulbOutlined: <BulbOutlined />,
    ThunderboltOutlined: <ThunderboltOutlined />,
    ExperimentOutlined: <ExperimentOutlined />,
    ScheduleOutlined: <ScheduleOutlined />,
    PieChartOutlined: <PieChartOutlined />,
    DesktopOutlined: <DesktopOutlined />,
    AlertOutlined: <AlertOutlined />,
    BarChartOutlined: <BarChartOutlined />,
    BankOutlined: <BankOutlined />,
    FormOutlined: <FormOutlined />,
    FundOutlined: <FundOutlined />,
};

/**
 * 根据图标名称获取图标组件
 * 优先从静态映射中查找，如果找不到且处于开发环境，则尝试动态加载并给出警告
 */
export const getIconFromMap = (iconName: string): React.ReactNode => {
    return CORE_ICON_MAP[iconName];
};
