services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  redis:
    image: "docker.io/library/redis:8.6"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    expose:
      - "6379"
    networks:
      - "aspire"
  mongo:
    image: "docker.io/library/mongo:8.2"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    expose:
      - "27017"
    volumes:
      - type: "volume"
        target: "/data/db"
        source: "platform.apphost-04e9402f01-mongo-data"
        read_only: false
    networks:
      - "aspire"
  datainitializer:
    image: "${DATAINITIALIZER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__database: "mongodb://admin:${MONGO_PASSWORD}@mongo:27017/platform-db-production?authSource=admin&authMechanism=SCRAM-SHA-256"
      DATABASE_HOST: "mongo"
      DATABASE_PORT: "27017"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "${MONGO_PASSWORD}"
      DATABASE_AUTHENTICATIONDATABASE: "admin"
      DATABASE_AUTHENTICATIONMECHANISM: "SCRAM-SHA-256"
      DATABASE_URI: "mongodb://admin:${MONGO_PASSWORD}@mongo:27017/platform-db-production?authSource=admin&authMechanism=SCRAM-SHA-256"
      DATABASE_DATABASENAME: "platform-db-production"
      Jwt__SecretKey: "w9G2xN7pR6qV3zL1s8F0bH5dT4jK2uM3"
      InternalService__ApiKey: "NyGHdYhwECvEQNFfM0CxpzYvC+1GRRMKRttaKkyOp5M="
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "datainitializer"
    depends_on:
      mongo:
        condition: "service_started"
    networks:
      - "aspire"
  apiservice:
    image: "${APISERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${APISERVICE_PORT}"
      Jwt__SecretKey: "w9G2xN7pR6qV3zL1s8F0bH5dT4jK2uM3"
      InternalService__ApiKey: "NyGHdYhwECvEQNFfM0CxpzYvC+1GRRMKRttaKkyOp5M="
      ConnectionStrings__database: "mongodb://admin:${MONGO_PASSWORD}@mongo:27017/platform-db-production?authSource=admin&authMechanism=SCRAM-SHA-256"
      DATABASE_HOST: "mongo"
      DATABASE_PORT: "27017"
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "${MONGO_PASSWORD}"
      DATABASE_AUTHENTICATIONDATABASE: "admin"
      DATABASE_AUTHENTICATIONMECHANISM: "SCRAM-SHA-256"
      DATABASE_URI: "mongodb://admin:${MONGO_PASSWORD}@mongo:27017/platform-db-production?authSource=admin&authMechanism=SCRAM-SHA-256"
      DATABASE_DATABASENAME: "platform-db-production"
      ConnectionStrings__chat: "Endpoint=https://free.v36.cm/v1;Key=${OPENAI_OPENAI_APIKEY};Model=gpt-4o-mini"
      CHAT_ENDPOINT: "https://free.v36.cm/v1"
      CHAT_URI: "https://free.v36.cm/v1"
      CHAT_KEY: "${OPENAI_OPENAI_APIKEY}"
      CHAT_MODELNAME: "gpt-4o-mini"
      ConnectionStrings__redis: "redis:6379,password=${REDIS_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_URI: "redis://:${REDIS_PASSWORD}@redis:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "apiservice"
    expose:
      - "${APISERVICE_PORT}"
    depends_on:
      mongo:
        condition: "service_started"
      redis:
        condition: "service_started"
    networks:
      - "aspire"
  admin:
    image: "${ADMIN_IMAGE}"
    environment:
      NODE_ENV: "production"
      PORT: "8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "admin"
    expose:
      - "8000"
    networks:
      - "aspire"
  apigateway:
    image: "${APIGATEWAY_IMAGE}"
    command:
      - "/app/yarp.dll"
    entrypoint:
      - "dotnet"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      YARP_ENABLE_STATIC_FILES: "true"
      REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/{**catchall}"
      REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_admin"
      REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/apiservice/{**catch-all}"
      REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_apiservice"
      REVERSEPROXY__ROUTES__route1__MAXREQUESTBODYSIZE: "-1"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__PathPattern: "/{**catch-all}"
      REVERSEPROXY__CLUSTERS__cluster_admin__DESTINATIONS__destination1__ADDRESS: "http://admin"
      REVERSEPROXY__CLUSTERS__cluster_apiservice__DESTINATIONS__destination1__ADDRESS: "http://apiservice"
      ADMIN_HTTP: "http://admin:8000"
      services__admin__http__0: "http://admin:8000"
      APISERVICE_HTTP: "http://apiservice:${APISERVICE_PORT}"
      services__apiservice__http__0: "http://apiservice:${APISERVICE_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "apigateway"
    ports:
      - "15000:5000"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  platform.apphost-04e9402f01-mongo-data:
    driver: "local"
