// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import SettingOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import UserOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TeamOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import MenuOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MenuOutlined';
import FileTextOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import BankOutlined from '/Volumes/thinkplus/Projects/aspire-admin/Platform.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BankOutlined';
export default { SmileOutlined, SettingOutlined, UserOutlined, TeamOutlined, MenuOutlined, FileTextOutlined, BankOutlined };
